### PR TITLE
Switch from CircleCI to Github Action workflows (closes #7)

### LINKED ISSUE #7: Use Github Action
The usage of CircleCI is still very little. I am not an expert on CicleCI, so I want to transfer my projects to using Github Action instead of CircleCI for the same purpose i.e. running tests :)

### PR DESCRIPTION
**Pull request by alexmisk**
Hi!

I've added a GitHub Actions workflow with the same functionality as with CircleCI (and the badge, of course!). The last commit deletes the old CircleCI workflow, but you can discard the commit and live with two CI systems if needed :-)

### CODE REVIEW

**Comment by yukinarit** [comment]
Awesome! Thank you! 👍

**Comment by alexmisk** [comment]
BTW you can "Rebase and merge" (see below) pull requests instead of creating a merge commit for a cleaner commit history.

**Comment by yukinarit** [comment]
Yes, I know but I rather want to keep the merge commit in the commit history like many other OSS on GitHub. Anyway thank you for the suggestion!

**Review by 888520ll19811209ll — APPROVED** [review]

**Comment by 888520ll19811209ll** [comment]
🙏

**Pull request merged**
